INSERT INTO City (city_Name, country_fk) values ("Barcelona", 1);
INSTERT INTO City (city_Name, country_fk)) values ("Valencja", 1);
INSTERT INTO City (city_Name, country_fk)) values ("Malaga", 1);
INSTERT INTO City (city_Name, country_fk)) values ("Ibiza", 1);
INSTERT INTO City (city_Name, country_fk)) values ("Saloniki", 2);
INSTERT INTO City (city_Name, country_fk)) values ("Platamonas", 2);
INSTERT INTO City (city_Name, country_fk)) values ("Santorini", 2);
INSTERT INTO City (city_Name, country_fk)) values ("Nicea", 3);
INSTERT INTO City (city_Name, country_fk)) values ("Saint Tropez", 3);
INSTERT INTO City (city_Name, country_fk)) values ("Paryż", 3);
INSTERT INTO City (city_Name, country_fk)) values ("Cannes", 3);
INSTERT INTO City (city_Name, country_fk)) values ("Dubrownik", 4);
INSTERT INTO City (city_Name, country_fk)) values ("Split", 4);
INSTERT INTO City (city_Name, country_fk)) values ("Marina", 4);
INSTERT INTO City (city_Name, country_fk)) values ("Pula", 4);
INSTERT INTO City (city_Name, country_fk)) values ("Lizbona", 5);
INSTERT INTO City (city_Name, country_fk)) values ("Porto", 5);
INSTERT INTO City (city_Name, country_fk)) values ("Faro", 5);
INSTERT INTO City (city_Name, country_fk)) values ("Fatima", 5);
INSTERT INTO City (city_Name, country_fk)) values ("Rzym", 6);
INSTERT INTO City (city_Name, country_fk)) values ("Wenecja", 6);
INSTERT INTO City (city_Name, country_fk)) values ("Bari", 6);
INSTERT INTO City (city_Name, country_fk)) values ("Palermo", 6);
INSTERT INTO City (city_Name, country_fk)) values ("Hurgada", 7);
INSTERT INTO City (city_Name, country_fk)) values ("Taba", 7);
INSTERT INTO City (city_Name, country_fk)) values ("Marsa Alam", 7);
INSTERT INTO City (city_Name, country_fk)) values ("Izmir", 8);
INSTERT INTO City (city_Name, country_fk)) values ("Antalya", 8);
INSTERT INTO City (city_Name, country_fk)) values ("Tunis", 9);
INSTERT INTO City (city_Name, country_fk)) values ("Hawana", 10);
INSTERT INTO City (city_Name, country_fk)) values ("Pattaya", 11);
INSTERT INTO City (city_Name, country_fk)) values ("Rio de Janeiro", 12);